import { Kembaliya } from "@/components/custom/pengembalian";

export default async function Page() {

    return (
        <>
            <Kembaliya items={[
                {
                    title: 'Inazuma',
                    nama: 'Ayu Dea',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '20 juni 2025',
                    status: true,
                    dikembali: '29 juni 2025',
                },
                {
                    title: 'Sejarah Indonesia',
                    nama: 'Siapapun',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '10 juni 2025',
                    status: false,
                    dikembali: '15 juni 2025',
                },
                {
                    title: 'Inazuma',
                    nama: 'Ayu Dea',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '20 juni 2025',
                    status: true,
                    dikembali: '29 juni 2025',
                },
                {
                    title: 'Sejarah Indonesia',
                    nama: 'Siapapun',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '10 juni 2025',
                    status: false,
                    dikembali: '15 juni 2025',
                },
                {
                    title: 'Inazuma',
                    nama: 'Ayu Dea',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '20 juni 2025',
                    status: true,
                    dikembali: '29 juni 2025',
                },
                {
                    title: 'Sejarah Indonesia',
                    nama: 'Siapapun',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '10 juni 2025',
                    status: false,
                    dikembali: '15 juni 2025',
                },
                {
                    title: 'Inazuma',
                    nama: 'Ayu Dea',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '20 juni 2025',
                    status: true,
                    dikembali: '29 juni 2025',
                },
                {
                    title: 'Sejarah Indonesia',
                    nama: 'Siapapun',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '10 juni 2025',
                    status: false,
                    dikembali: '15 juni 2025',
                },
                {
                    title: 'Inazuma',
                    nama: 'Ayu Dea',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '20 juni 2025',
                    status: true,
                    dikembali: '29 juni 2025',
                },
                {
                    title: 'Sejarah Indonesia',
                    nama: 'Siapapun',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '10 juni 2025',
                    status: false,
                    dikembali: '15 juni 2025',
                },
                {
                    title: 'Inazuma',
                    nama: 'Ayu Dea',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '20 juni 2025',
                    status: true,
                    dikembali: '29 juni 2025',
                },
                {
                    title: 'Inazuma',
                    nama: 'Ayu Dea',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '20 juni 2025',
                    status: true,
                    dikembali: '29 juni 2025',
                },
                {
                    title: 'Sejarah Indonesia',
                    nama: 'Siapapun',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '10 juni 2025',
                    status: false,
                    dikembali: '15 juni 2025',
                },
                {
                    title: 'Inazuma',
                    nama: 'Ayu Dea',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '20 juni 2025',
                    status: true,
                    dikembali: '29 juni 2025',
                },
                {
                    title: 'Sejarah Indonesia',
                    nama: 'Siapapun',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '10 juni 2025',
                    status: false,
                    dikembali: '15 juni 2025',
                },
                {
                    title: 'Inazuma',
                    nama: 'Ayu Dea',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '20 juni 2025',
                    status: true,
                    dikembali: '29 juni 2025',
                },
                {
                    title: 'Sejarah Indonesia',
                    nama: 'Siapapun',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '10 juni 2025',
                    status: false,
                    dikembali: '15 juni 2025',
                },
                {
                    title: 'Inazuma',
                    nama: 'Ayu Dea',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '20 juni 2025',
                    status: true,
                    dikembali: '29 juni 2025',
                },
                {
                    title: 'Sejarah Indonesia',
                    nama: 'Siapapun',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '10 juni 2025',
                    status: false,
                    dikembali: '15 juni 2025',
                },
                {
                    title: 'Inazuma',
                    nama: 'Ayu Dea',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '20 juni 2025',
                    status: true,
                    dikembali: '29 juni 2025',
                },
                {
                    title: 'Sejarah Indonesia',
                    nama: 'Siapapun',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '10 juni 2025',
                    status: false,
                    dikembali: '15 juni 2025',
                },
                {
                    title: 'Inazuma',
                    nama: 'Ayu Dea',
                    Peminjaman: '11 juni 2025, 08.00',
                    Pengembalian: '20 juni 2025',
                    status: true,
                    dikembali: '29 juni 2025',
                },
            ]}/>
        </>
    );
}